/*
 * File: app/store/ASGroupListStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.store.ASGroupListStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Peacock.model.ASGroupModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'Peacock.model.ASGroupModel',
            proxy: {
                type: 'ajax',
                url: 'static/asGroupList.json',
                reader: {
                    type: 'json',
                    root: 'list'
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onJsonstoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonstoreBeforeLoad: function(store, operation, eOpts) {

        Peacock.app.debug("ASGroupListStore.onBeforeLoad.");

        Ext.getCmp('detailPanel').removeAll(true);
    }

});