/*
 * File: app/store/UsersJsonStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.store.UsersJsonStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Peacock.model.UsersModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            model: 'Peacock.model.UsersModel',
            storeId: 'UsersJsonStore',
            pageSize: 10,
            proxy: {
                type: 'ajax',
                url: 'static/users.json',
                reader: {
                    type: 'json',
                    root: 'users'
                }
            }
        }, cfg)]);
    }
});