/*
 * File: app/controller/GlobalAjaxController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.controller.GlobalAjaxController', {
    extend: 'Ext.app.Controller',

    init: function(application) {

        //Peacock.app.debug("GlobalAjaxController.init." ); // 에러남.

        Ext.Ajax.on("requestexception", function(conn, response, options, eOpts){


            Ext.Msg.show({
                title:'Server Error',
                msg: 'server-side failure with status code ' + response.status,
                buttons: Ext.Msg.OK,
                icon: Ext.Msg.ERROR
            });
        });
    }

});
