/*
 * File: app/controller/MainToolbarController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.controller.MainToolbarController', {
    extend: 'Ext.app.Controller',

    onButtonClick: function(button, e, eOpts) {
        Peacock.app.debug("MainToolbarController.mainButton click. " + Peacock.app.menu_id);


        if (Peacock.app.menu_id == 'insts'){

            var win = Ext.widget('instanceLaunchWindow');
            win.show();

        }else if (Peacock.app.menu_id == 'img-tmp'){


        }else if (Peacock.app.menu_id == 'img-pkg'){


        }else if (Peacock.app.menu_id == 'scal-grp'){


        }else if (Peacock.app.menu_id == 'scal-lb'){


        }else if (Peacock.app.menu_id == 'user-grp'){

            var win = Ext.widget('userGroupFormWindow');
            win.show();


            /*
            Ext.getCmp("userGroupForm").getForm().load({
            url : "static/groupSummary.json"
            });
            */

        }else if (Peacock.app.menu_id == 'users'){



        }
    },

    onMenuitemClick: function(item, e, eOpts) {
        alert(item.getId());
    },

    init: function(application) {
        this.control({
            "#mainToolbar #mainButton": {
                click: this.onButtonClick
            },
            "#mainToolba menuitem": {
                click: this.onMenuitemClick
            }
        });
    }

});
