/*
 * File: app/controller/TopToolbarController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.controller.TopToolbarController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'viewport',
            selector: 'mainView'
        }
    ],

    onMenuitemClick: function(item, e, eOpts) {

        if(item.getId() == "topMyAccountMenu"){

            Ext.widget('userFormWindow').show();

            var formPanel = Ext.getCmp("userForm");

            formPanel.up('window').setTitle("My Account");

            formPanel.getForm().load({
                params : {
                    user_id : Peacock.app.loginUser.user_id
                },
                url : "user/getUser",
                waitMsg: 'Loading...'
            });

        }else if(item.getId() == "topLogOutMenu"){

            var viewport = this.getViewport();

            Ext.Ajax.request({
                url: 'user/logout',
                disableCaching : true,
                success: function(response){
                    //var text = response.responseText;
                    //alert(text);

                    viewport.layout.setActiveItem(0);
                }
            });



        }
    },

    init: function(application) {
        this.control({
            "#topToolbar menuitem": {
                click: this.onMenuitemClick
            }
        });
    }

});
