/*
 * File: app/controller/UsersTabPanelController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.controller.UsersTabPanelController', {
    extend: 'Ext.app.Controller',

    views: [
        'UserTabPanel'
    ],

    onTabpanelTabChange: function(tabPanel, newCard, oldCard, eOpts) {
        if(newCard.title == "Groups"){

            this.viewGroups();

        }else if(newCard.title == "Summary"){


            /*
            * User > Summary Tab 화면 조회.
            */

            var grid1 = Ext.getCmp("userSummaryGrid");

            var jsonObj;

            Ext.Ajax.request({
                url: 'static/userSummary.json',
                params: {
                    id: 1
                },
                success: function(response){
                    var jsonObj = Ext.JSON.decode(response.responseText);

                    grid1.setSource(jsonObj);
                }
            });


        }
    },

    onTabpanelAdded: function(component, container, pos, eOpts) {
        this.viewGroups();
    },

    viewGroups: function() {

        /*
        * User > Groups Tab 화면 조회.
        */

        var grid = Ext.getCmp("userGroupsGrid");

        grid.getStore().load();
    },

    init: function(application) {
        this.control({
            "userTabPanel": {
                tabchange: this.onTabpanelTabChange,
                added: this.onTabpanelAdded
            }
        });
    }

});
