/*
 * File: app/controller/InstanceTabPanelController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.controller.InstanceTabPanelController', {
    extend: 'Ext.app.Controller',

    views: [
        'InstanceTabPanel'
    ],

    onTabpanelTabChange: function(tabPanel, newCard, oldCard, eOpts) {
        alert("tabpanel change!!.");
    },

    onTabpanelAdded: function(component, container, pos, eOpts) {
        /*
        * 초기 화면 조회시. (목록에서 선택시)
        */

        //var tabPanel = this.getInstanceTabPanelView();
        var grid1 = Ext.getCmp("instDescGrid1");
        grid1.setSource({aaa : "aaaa11"});

    },

    init: function(application) {
        this.control({
            "instanceTabPanel": {
                tabchange: this.onTabpanelTabChange,
                added: this.onTabpanelAdded
            }
        });
    }

});
