/*
 * File: app/controller/MenuController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.controller.MenuController', {
    extend: 'Ext.app.Controller',

    onTreepanelItemClick: function(dataview, record, item, index, e, eOpts) {
        if(record.get('id') == 'inst-dash'){
            //alert("instance dash board.");
            Ext.getCmp('centerContainer').layout.setActiveItem(0);

        }else if (record.get('id') == 'insts'){
            //alert("instances.");

            Ext.getCmp('centerContainer').layout.setActiveItem(1);

        }else if (record.get('id') == 'img-tmp'){
            alert("templates.");

        }else if (record.get('id') == 'img-pkg'){
            alert("packages.");

        }else if (record.get('id') == 'scal-grp'){
            alert("scal-grp.");

        }else if (record.get('id') == 'scal-lb'){
            alert("scal-lb.");

        }else if (record.get('id') == 'user-grp'){
            alert("user-grp.");

        }else if (record.get('id') == 'users'){
            alert("users.");

        }
    },

    init: function(application) {
        this.control({
            "#westPanel treepanel": {
                itemclick: this.onTreepanelItemClick
            }
        });
    }

});
