/*
 * File: app/view/InstanceLaunchWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.view.InstanceLaunchWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.instanceLaunchWindow',

    height: 475,
    width: 674,
    title: 'Instance Launch Wizard',
    modal: true,

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});