/*
 * File: app/view/SWInstallLaunchWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.view.SWInstallLaunchWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.swInstallLaunchWindow',

    height: 431,
    id: 'swInstallWin',
    width: 711,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: 'Software Install Launch Wizard',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    height: 100,
                    layout: {
                        pack: 'center',
                        padding: '0 10',
                        type: 'vbox'
                    },
                    header: false,
                    title: 'My Panel',
                    items: [
                        {
                            xtype: 'combobox',
                            id: 'softwareCombo',
                            fieldLabel: 'Software',
                            displayField: 'name',
                            queryMode: 'local',
                            store: 'SoftwareComboStore',
                            valueField: 'value'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 8,
                    id: 'swParamPanel',
                    layout: {
                        type: 'card'
                    },
                    header: false,
                    title: 'Param Panel',
                    items: [
                        {
                            xtype: 'form',
                            id: 'apache',
                            bodyPadding: 10,
                            header: false,
                            title: 'ApacheParamForm',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Apache Install',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '40%',
                                            afterLabelTextTpl: [
                                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                            ],
                                            fieldLabel: 'Version',
                                            name: 'version',
                                            allowBlank: false,
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: [
                                                '2.2.25',
                                                '2.4.4'
                                            ]
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'apacheTargetDir',
                                            fieldLabel: 'Target Dir',
                                            name: 'targetDir',
                                            value: [
                                                '/usr/local/apache'
                                            ]
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            id: 'apacheServerRoot',
                                            fieldLabel: 'Server Root',
                                            name: 'serverRoot',
                                            value: [
                                                '/usr/local/apache'
                                            ]
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '30%',
                                            fieldLabel: 'Port',
                                            name: 'port',
                                            value: [
                                                '80'
                                            ],
                                            vtype: 'numeric'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '50%',
                                            fieldLabel: 'Server Domain',
                                            name: 'serverDomain',
                                            value: [
                                                'localhost'
                                            ]
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Start Service',
                                            name: 'autoStart',
                                            boxLabel: 'Start Service after Installation ',
                                            checked: true,
                                            inputValue: 'Y',
                                            uncheckedValue: 'N'
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                afterrender: {
                                    fn: me.onApacheAfterRender,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'form',
                            id: 'tomcat',
                            bodyPadding: 10,
                            header: false,
                            title: 'TomcatParamForm',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Tomcat Install',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '40%',
                                            afterLabelTextTpl: [
                                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                            ],
                                            fieldLabel: 'Version',
                                            name: 'version',
                                            allowBlank: false,
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: [
                                                '6.0.37'
                                            ]
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '50%',
                                            afterLabelTextTpl: [
                                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                            ],
                                            fieldLabel: 'Java Home',
                                            name: 'javaHome',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            afterLabelTextTpl: [
                                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                            ],
                                            fieldLabel: 'Catalina Home',
                                            name: 'catalinaHome',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            afterLabelTextTpl: [
                                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                            ],
                                            fieldLabel: 'Catalina Base',
                                            name: 'catalinaBase',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '50%',
                                            afterLabelTextTpl: [
                                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                            ],
                                            fieldLabel: 'Server Name',
                                            name: 'serverName',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '40%',
                                            afterLabelTextTpl: [
                                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                            ],
                                            fieldLabel: 'Comp User',
                                            name: 'compUser',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '30%',
                                            fieldLabel: 'Port Offset',
                                            name: 'portOffset',
                                            value: [
                                                '0'
                                            ],
                                            vtype: 'numeric'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Start Service',
                                            name: 'autoStart',
                                            boxLabel: 'Start Service after Installation ',
                                            checked: true,
                                            inputValue: 'Y',
                                            uncheckedValue: 'N'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            id: 'jboss',
                            autoScroll: true,
                            bodyPadding: 10,
                            header: false,
                            title: 'JBossParamForm',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'JBoss Install',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '40%',
                                            afterLabelTextTpl: [
                                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                            ],
                                            fieldLabel: 'Version',
                                            name: 'version',
                                            allowBlank: false,
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: [
                                                '5.2.0'
                                            ]
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '50%',
                                            afterLabelTextTpl: [
                                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                            ],
                                            fieldLabel: 'Java Home',
                                            name: 'javaHome',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '50%',
                                            afterLabelTextTpl: [
                                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                            ],
                                            fieldLabel: 'JBoss Home',
                                            name: 'jbossHome',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '80%',
                                            afterLabelTextTpl: [
                                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                            ],
                                            fieldLabel: 'Server Home',
                                            name: 'serverHome',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '50%',
                                            afterLabelTextTpl: [
                                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                            ],
                                            fieldLabel: 'Server Name',
                                            name: 'serverName',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '50%',
                                            fieldLabel: 'Partition Name',
                                            name: 'partitionName',
                                            value: [
                                                'partition'
                                            ]
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '50%',
                                            fieldLabel: 'Bind Address',
                                            name: 'bindAddress',
                                            value: [
                                                '0.0.0.0'
                                            ]
                                        },
                                        {
                                            xtype: 'combobox',
                                            anchor: '40%',
                                            fieldLabel: 'Bind Port',
                                            name: 'bindPort',
                                            value: [
                                                'ports-default'
                                            ],
                                            allowBlank: false,
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: [
                                                'ports-default',
                                                'ports-01',
                                                'ports-02',
                                                'ports-03'
                                            ]
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Start Service',
                                            name: 'autoStart',
                                            boxLabel: 'Start Service after Installation ',
                                            checked: true,
                                            inputValue: 'Y',
                                            uncheckedValue: 'N'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    collapsed: true,
                                    collapsible: true,
                                    title: 'Data Source Setting [Optional]',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '40%',
                                            fieldLabel: 'Database Type',
                                            name: 'databaseType',
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: [
                                                'mysql',
                                                'oracle',
                                                'cubrid'
                                            ]
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '60%',
                                            fieldLabel: 'JNDI Name',
                                            name: 'jndiName'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'JDBC URL',
                                            name: 'connectionUrl'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '50%',
                                            fieldLabel: 'User Name',
                                            name: 'userName'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '50%',
                                            fieldLabel: 'Password',
                                            name: 'Password',
                                            inputType: 'password',
                                            emptyText: '',
                                            maxLength: 20,
                                            minLength: 4
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '50%',
                                            fieldLabel: 'Min Pool Size',
                                            name: 'minPoolSize',
                                            value: [
                                                '10'
                                            ]
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '50%',
                                            fieldLabel: 'Max Pool Size',
                                            name: 'maxPoolSize',
                                            value: [
                                                '20'
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            id: 'mysql',
                            bodyPadding: 10,
                            header: false,
                            title: 'MySQLParamForm',
                            fieldDefaults: {
                                msgTarget: 'side',
                                labelWidth: 120
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'MySQL Install',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '40%',
                                            afterLabelTextTpl: [
                                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                                            ],
                                            fieldLabel: 'Version',
                                            name: 'version',
                                            allowBlank: false,
                                            forceSelection: true,
                                            queryMode: 'local',
                                            store: [
                                                '5.5.34'
                                            ]
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Data Dir',
                                            name: 'dataDir',
                                            value: [
                                                '/var/lib/mysql'
                                            ]
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '30%',
                                            fieldLabel: 'Port',
                                            name: 'port',
                                            value: [
                                                '3306'
                                            ],
                                            vtype: 'numeric'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '50%',
                                            fieldLabel: 'Password',
                                            name: 'password',
                                            inputType: 'password',
                                            emptyText: '4 ~ 20자',
                                            maxLength: 20,
                                            minLength: 4
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Start Service',
                                            name: 'autoStart',
                                            boxLabel: 'Start Service after Installation ',
                                            checked: true,
                                            inputValue: 'Y',
                                            uncheckedValue: 'N'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    ui: 'footer',
                    layout: {
                        pack: 'center',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'Launch',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Cancel',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick1,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onApacheAfterRender: function(component, eOpts) {

        /*
        * Tooltip Config.
        */

        Peacock.app.debug("ApacheParamForm.onApacheAfterRender.");

        var tooltipConfigs = [
        {target:"apacheTargetDir", html : "This is targetDir"},
        {target:"apacheServerRoot", html : "This is serverRoot"}
        ];

        Ext.each(tooltipConfigs, function(config) {
            Ext.create('Ext.tip.ToolTip', {
                target: config.target,
                html: config.html
            });
        });





    },

    onButtonClick: function(button, e, eOpts) {

        var record = Peacock.app.selectedRecord;
        var swCombo = Ext.getCmp("softwareCombo");


        var paramPanel = Ext.getCmp("swParamPanel");
        var formPanel = paramPanel.layout.getActiveItem();

        formPanel.getForm().submit({
            clientValidation: true,
            url: "software/install",
            params: {
                machineId: record.get("machineId"),
                softwareId: swCombo.getValue()
            },
            waitMsg: 'Saving Data...',
            success: function(form, action) {
                Ext.Msg.alert('Success', action.result.msg);

                formPanel.up('window').close();
            },
            failure: function(form, action) {
                switch (action.failureType) {
                    case Ext.form.action.Action.CLIENT_INVALID:
                    Ext.Msg.alert('Failure', '유효하지 않은 입력값이 존재합니다.');
                    break;
                    case Ext.form.action.Action.CONNECT_FAILURE:
                    Ext.Msg.alert('Failure', 'Server communication failed');
                    break;
                    case Ext.form.action.Action.SERVER_INVALID:
                    Ext.Msg.alert('Failure', action.result.msg);
                }
            }
        });
    },

    onButtonClick1: function(button, e, eOpts) {
        /*
        Ext.MessageBox.confirm('Confirm', 'Are you sure you want to do that?', function(btn){

        if(btn == "yes"){

        }

        });
        */

        Ext.getCmp("swParamPanel").up("window").close();
    }

});