/*
 * File: app/view/SWLogWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.view.SWLogWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.swLogWindow',

    height: 537,
    width: 700,
    layout: {
        type: 'fit'
    },
    title: 'Software Install Log',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    waitMsgTarget: true,
                    items: [
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            flex: 1,
                            fieldLabel: 'Install Log',
                            labelAlign: 'top',
                            name: 'installLog'
                        }
                    ]
                }
            ],
            listeners: {
                show: {
                    fn: me.onWindowShow,
                    scope: me
                }
            },
            tools: [
                {
                    xtype: 'tool',
                    handler: function(event, toolEl, owner, tool) {

                    },
                    tooltip: 'Refresh',
                    type: 'refresh'
                }
            ]
        });

        me.callParent(arguments);
    },

    onWindowShow: function(component, eOpts) {
        var formPanel = component.down("form");

        formPanel.getForm().load({
            params : {
                machineId : Peacock.app.selectedRecord.get("machineId"),
                softwareId : component.swid
            },
            url : "software/getInstallLog",
            waitMsg: 'Loading...'
        });
    }

});