/*
 * File: app/view/UserGroupTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.view.UserGroupTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.userGroupTabPanel',

    height: 291,
    width: 765,
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    title: 'Users',
                    items: [
                        {
                            xtype: 'gridpanel',
                            id: 'groupUsersGrid',
                            header: false,
                            title: 'My Grid Panel',
                            store: 'UserGroupMapStore',
                            columns: [
                                {
                                    xtype: 'rownumberer'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'user_name',
                                    text: 'User'
                                },
                                {
                                    xtype: 'actioncolumn',
                                    align: 'center',
                                    items: [
                                        {
                                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                alert("Delete "+ record.get("user_name"));
                                            },
                                            icon: 'resources/icons/fam/delete.gif',
                                            tooltip: 'Delete'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Summary',
                    items: [
                        {
                            xtype: 'propertygrid',
                            id: 'groupSummaryGrid',
                            header: false,
                            title: 'My Property Grid',
                            sortableColumns: false,
                            source: {
                                'Property 1': 'String',
                                'Property 2': true,
                                'Property 3': '2013-08-22T13:52:51',
                                'Property 4': 123
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});