/*
 * File: app/model/ASGroupModel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.model.ASGroupModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'as_group_id',
            type: 'int'
        },
        {
            name: 'as_group_name',
            type: 'string'
        },
        {
            name: 'min_size',
            type: 'int'
        },
        {
            name: 'max_size',
            type: 'int'
        },
        {
            name: 'launch_config_id',
            type: 'string'
        },
        {
            name: 'reg_user_id',
            type: 'int'
        },
        {
            name: 'reg_dt',
            type: 'string'
        },
        {
            name: 'upd_user_id',
            type: 'int'
        },
        {
            name: 'upd_dt',
            type: 'string'
        }
    ]
});