/*
 * File: app/model/MachineModel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.model.MachineModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'machineId',
            type: 'string'
        },
        {
            name: 'machineMacAddr',
            type: 'string'
        },
        {
            name: 'machine_name',
            type: 'string'
        },
        {
            name: 'template',
            type: 'string'
        },
        {
            name: 'status',
            type: 'string'
        },
        {
            name: 'uptime',
            type: 'string'
        },
        {
            name: 'hostName',
            type: 'string'
        },
        {
            name: 'isVm',
            type: 'boolean'
        },
        {
            name: 'osName',
            type: 'string'
        },
        {
            name: 'osVer',
            type: 'string'
        },
        {
            name: 'osArch',
            type: 'string'
        },
        {
            name: 'cpuClock',
            type: 'string'
        },
        {
            name: 'cpuNum',
            type: 'int'
        },
        {
            name: 'memSize',
            type: 'string'
        },
        {
            name: 'ipAddr',
            type: 'string'
        },
        {
            name: 'regDt',
            type: 'string'
        }
    ]
});