/*
 * File: app/model/OSPackageModel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.model.OSPackageModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'pkgId',
            type: 'int'
        },
        {
            name: 'name',
            type: 'string'
        },
        {
            name: 'arch',
            type: 'string'
        },
        {
            name: 'version',
            type: 'string'
        },
        {
            name: 'releaseInfo',
            type: 'string'
        },
        {
            name: 'size',
            type: 'string'
        },
        {
            name: 'installDate',
            type: 'string'
        },
        {
            name: 'summary',
            type: 'string'
        },
        {
            name: 'description',
            type: 'string'
        }
    ]
});