/*
 * File: app/model/SoftwareModel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Peacock.model.SoftwareModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'software_id',
            type: 'int'
        },
        {
            name: 'software_name',
            type: 'string'
        },
        {
            name: 'version',
            type: 'string'
        },
        {
            name: 'repo_location',
            type: 'string'
        },
        {
            name: 'software_file_name',
            type: 'string'
        },
        {
            name: 'vendor_name',
            type: 'string'
        },
        {
            name: 'description',
            type: 'string'
        },
        {
            name: 'register_dt',
            type: 'string'
        },
        {
            name: 'engine_dir',
            type: 'string'
        },
        {
            name: 'install_dt',
            type: 'string'
        }
    ]
});